import type { SeedData } from '@/lib/types';

export const seoulSeedData: SeedData = {
  "trip": {
    "id": "seoul-2026-05",
    "title": "2026 Seoul Trip",
    "destination": "Seoul, Korea",
    "baseArea": "Hongdae",
    "hotel": "Maple Mansion Hongdae",
    "startDate": "2026-05-24",
    "endDate": "2026-05-31",
    "departureDate": "2026-05-24",
    "coverImage": "",
    "status": "planning"
  },
  "days": [
    {"id":"day-1","dayNumber":1,"date":"2026-05-24","title":"Arrival Day","district":"Hongdae","weather":{"condition":"Partly Cloudy","icon":"cloud-sun","minC":16,"maxC":23}},
    {"id":"day-2","dayNumber":2,"date":"2026-05-25","title":"Hongdae → Yeonnam → Hangang","district":"Hongdae / Yeonnam / Mangwon","weather":{"condition":"Cloudy","icon":"cloud","minC":17,"maxC":24}},
    {"id":"day-3","dayNumber":3,"date":"2026-05-26","title":"Seongsu Aesthetic Day","district":"Seongsu","weather":{"condition":"Sunny","icon":"sun","minC":18,"maxC":25}},
    {"id":"day-4","dayNumber":4,"date":"2026-05-27","title":"Bukchon → Geumdwaeji → Jung-gu Night Walk","district":"Bukchon / Yaksu / Jung-gu","weather":{"condition":"Partly Cloudy","icon":"cloud-sun","minC":17,"maxC":24}},
    {"id":"day-5","dayNumber":5,"date":"2026-05-28","title":"Myeongdong → Cheonggyecheon → N Seoul Tower","district":"Myeongdong / Jung-gu / Namsan","weather":{"condition":"Clear","icon":"sun","minC":18,"maxC":26}},
    {"id":"day-6","dayNumber":6,"date":"2026-05-29","title":"Friend Dinner Day","district":"Hongdae / Yeonnam / Sinchon","weather":{"condition":"Cloudy","icon":"cloud","minC":18,"maxC":25}},
    {"id":"day-7","dayNumber":7,"date":"2026-05-30","title":"Clinic Day","district":"Hongdae / Yeonnam","weather":{"condition":"Partly Cloudy","icon":"cloud-sun","minC":17,"maxC":23}},
    {"id":"day-8","dayNumber":8,"date":"2026-05-31","title":"Departure Day","district":"Hongdae / Airport","weather":{"condition":"Sunny","icon":"sun","minC":18,"maxC":24}}
  ],
  "activities": [
    {"id":"a-1-1","dayId":"day-1","title":"Check-in Maple Mansion Hongdae","category":"hotel","time":"17:30","place":"Maple Mansion Hongdae","note":"Arrival and hotel check-in.","cost":0,"order":1},
    {"id":"a-1-2","dayId":"day-1","title":"Dinner at Hotel De GGOODD","category":"food","time":"18:00","place":"Hotel De GGOODD","note":"7 Donggyo-ro 46-gil, Mapo-gu. Walk from hotel.","cost":0,"order":2},
    {"id":"a-1-3","dayId":"day-1","title":"Hongdae Main Street Walk","category":"sightseeing","time":"20:00","place":"Hongdae Main Street","note":"First night: get familiar, buy water, enjoy the vibe.","cost":0,"order":3},
    {"id":"a-1-4","dayId":"day-1","title":"Hongdae Alleys / Stationery / Convenience Store","category":"shopping","time":"21:30","place":"Hongdae backstreets","note":"Slow walk into smaller alleys and stores.","cost":0,"order":4},
    {"id":"a-1-5","dayId":"day-1","title":"Optional Yeonnam Walk or Return Hotel","category":"other","time":"22:30","place":"Yeonnam / Hotel","note":"If still energetic, walk a bit toward Yeonnam; otherwise return.","cost":0,"order":5},
    {"id":"a-2-1","dayId":"day-2","title":"Hongdae Café / Light Street Walk","category":"cafe","time":"14:00","place":"Hongdae","note":"Do not eat too much before garlic bread and dinner.","cost":0,"order":1},
    {"id":"a-2-2","dayId":"day-2","title":"Mandong Bakery Yeonnam","category":"food","time":"15:30","place":"Mandong Bakery Yeonnam","note":"Buy garlic bread. Walk from Hongdae to Yeonnam.","cost":0,"order":2},
    {"id":"a-2-3","dayId":"day-2","title":"Yeonnam-dong Walk","category":"sightseeing","time":"16:00","place":"Yeonnam-dong","note":"Street shops, select stores, photos. No extra café stop needed.","cost":0,"order":3},
    {"id":"a-2-4","dayId":"day-2","title":"Dinner at CAMELLO Yeonnam","category":"food","time":"19:00","place":"CAMELLO Yeonnam","note":"Walk or take a short taxi depending on position in Yeonnam.","cost":0,"order":4},
    {"id":"a-2-5","dayId":"day-2","title":"Mangwon Hangang Park","category":"sightseeing","time":"21:00","place":"Mangwon Hangang Park","note":"Take taxi from CAMELLO. Say 망원한강공원.","cost":0,"order":5},
    {"id":"a-2-6","dayId":"day-2","title":"Saebyeok Hongdae Bar & Pub","category":"other","time":"23:15","place":"Saebyeok Hongdae Bar & Pub","note":"Return by taxi from Hangang. Keep drinks light.","cost":0,"order":6},
    {"id":"a-3-1","dayId":"day-3","title":"Cafe Onion Seongsu","category":"cafe","time":"14:00","place":"Cafe Onion Seongsu","note":"Take subway from Hongik Univ. Station to Seongsu Station, Exit 2.","cost":0,"order":1},
    {"id":"a-3-2","dayId":"day-3","title":"EMPTY / Pop-up / Select Shops","category":"shopping","time":"16:30","place":"Seongsu","note":"Main value is slow walking through the neighborhood.","cost":0,"order":2},
    {"id":"a-3-3","dayId":"day-3","title":"Dinner at Seongsu Darak","category":"food","time":"19:00","place":"Seongsu Darak","note":"Walkable from Seongsu Station Exit 3 area.","cost":0,"order":3},
    {"id":"a-3-4","dayId":"day-3","title":"Seongsu Night Walk","category":"sightseeing","time":"20:45","place":"Seongsu streets","note":"No Gangnam today. Keep flow within Seongsu only.","cost":0,"order":4},
    {"id":"a-4-1","dayId":"day-4","title":"Bukchon Hanok Village","category":"sightseeing","time":"14:00","place":"Bukchon Hanok Village","note":"Go via Anguk Station Exit 3. Keep it slow.","cost":0,"order":1},
    {"id":"a-4-2","dayId":"day-4","title":"Nearby Café / Tea Break","category":"cafe","time":"16:00","place":"Bukchon / Anguk area","note":"Buffer before heading to Geumdwaeji Sikdang.","cost":0,"order":2},
    {"id":"a-4-3","dayId":"day-4","title":"Travel to Geumdwaeji Sikdang","category":"transport","time":"16:40","place":"Yaksu Station","note":"Go around 17:00 for queue. Use subway to Yaksu Station Exit 2.","cost":0,"order":3},
    {"id":"a-4-4","dayId":"day-4","title":"Dinner at Geumdwaeji Sikdang","category":"food","time":"17:30","place":"Geumdwaeji Sikdang","note":"Timing flexible depending on queue.","cost":0,"order":4},
    {"id":"a-4-5","dayId":"day-4","title":"Jung-gu Night Walk","category":"sightseeing","time":"19:30","place":"Jung-gu","note":"If queue runs long, shorten this and just do nearby walk.","cost":0,"order":5},
    {"id":"a-5-1","dayId":"day-5","title":"Myeongdong Shopping","category":"shopping","time":"14:00","place":"Myeongdong","note":"Only snacks, no full meal before evening flow.","cost":0,"order":1},
    {"id":"a-5-2","dayId":"day-5","title":"Cheonggyecheon Best Section Walk","category":"sightseeing","time":"18:00","place":"Cheonggye Plaza → Gwangtong Bridge → Supyo Bridge","note":"Focus on the most atmospheric stretch near dusk.","cost":0,"order":2},
    {"id":"a-5-3","dayId":"day-5","title":"Travel to N Seoul Tower Bus Stop","category":"transport","time":"19:00","place":"Chungmuro Station Exit 2 / Dongguk Univ. Station Exit 6","note":"Take 01A/01B Namsan circular bus. Taxi fallback if needed.","cost":0,"order":3},
    {"id":"a-5-4","dayId":"day-5","title":"N Seoul Tower","category":"sightseeing","time":"19:30","place":"N Seoul Tower","note":"Evening visit.","cost":0,"order":4},
    {"id":"a-5-5","dayId":"day-5","title":"Convenience Store Supper","category":"food","time":"21:30","place":"Convenience store","note":"Ramen, rice ball, fried snack, drink.","cost":0,"order":5},
    {"id":"a-5-6","dayId":"day-5","title":"Return Hotel / Light Night Walk","category":"other","time":"22:30","place":"Hongdae / Hotel","note":"Optional light walk after returning.","cost":0,"order":6},
    {"id":"a-6-1","dayId":"day-6","title":"Hongdae / Yeonnam / Sinchon Slow Walk","category":"sightseeing","time":"14:00","place":"Hongdae / Yeonnam / Sinchon","note":"Keep daytime flexible because of evening dinner with friend.","cost":0,"order":1},
    {"id":"a-6-2","dayId":"day-6","title":"Café Break","category":"cafe","time":"17:30","place":"Hongdae / Yeonnam","note":"Sit down, reset, and wait for dinner.","cost":0,"order":2},
    {"id":"a-6-3","dayId":"day-6","title":"Dinner at Ilpyeon Deungsim Hongdae","category":"food","time":"19:00","place":"Ilpyeon Deungsim Hongdae","note":"Walk or short taxi depending on location.","cost":0,"order":3},
    {"id":"a-6-4","dayId":"day-6","title":"Hongdae Night Walk / Second Round","category":"other","time":"21:30","place":"Hongdae","note":"Follow friend’s pace, but avoid drinking too much.","cost":0,"order":4},
    {"id":"a-7-1","dayId":"day-7","title":"PPEUM Global Clinic Hongdae","category":"other","time":"14:00","place":"PPEUM Global Clinic Hongdae","note":"H-Cube 4F, 140 Yanghwa-ro. Near Hongik Univ. Station Exit 9.","cost":0,"order":1},
    {"id":"a-7-2","dayId":"day-7","title":"Café Rest","category":"cafe","time":"16:30","place":"Hongdae / Yeonnam","note":"Avoid strong sun, sweat, alcohol after Botox.","cost":0,"order":2},
    {"id":"a-7-3","dayId":"day-7","title":"Light Dinner at Donsubaek / Donsoobaek","category":"food","time":"19:00","place":"Donsubaek / Donsoobaek","note":"Keep meal light, no alcohol, not too spicy or salty.","cost":0,"order":3},
    {"id":"a-7-4","dayId":"day-7","title":"Hongdae / Yeonnam Light Walk","category":"sightseeing","time":"20:30","place":"Hongdae / Yeonnam","note":"Comfortable easy walk only.","cost":0,"order":4},
    {"id":"a-7-5","dayId":"day-7","title":"Night Café","category":"cafe","time":"23:00","place":"Hongdae / Yeonnam","note":"Sit down and end the day quietly.","cost":0,"order":5},
    {"id":"a-7-6","dayId":"day-7","title":"Return Hotel","category":"hotel","time":"23:40","place":"Maple Mansion Hongdae","note":"Back to hotel.","cost":0,"order":6},
    {"id":"a-8-1","dayId":"day-8","title":"Brunch near Hongdae","category":"food","time":"09:30","place":"Hongdae","note":"Stay nearby, do not go far before airport transfer.","cost":0,"order":1},
    {"id":"a-8-2","dayId":"day-8","title":"Leave Hotel for Airport","category":"transport","time":"11:30","place":"Hongik Univ. Station → Airport","note":"Use airport line from Hongik Univ. Station.","cost":0,"order":2}
  ]
};
